/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessIndexRouteImport } from './routes/success/index'
import { Route as QuestionnaireIndexRouteImport } from './routes/questionnaire/index'
<<<<<<< HEAD
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminPostPostsRouteImport } from './routes/admin/post/posts'
import { Route as AdminPostPostsIndexRouteImport } from './routes/admin/post/posts.index'
=======
import { Route as QuestionnaireSegmentedIndexRouteImport } from './routes/questionnaire/segmented/index'
import { Route as AuthedPostPostsRouteImport } from './routes/_authed/post/posts'
import { Route as AuthedPostPostsIndexRouteImport } from './routes/_authed/post/posts.index'
>>>>>>> 4bc6defafec6f7a5b40d3e276d0da4e09cc162ad

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessIndexRoute = SuccessIndexRouteImport.update({
  id: '/success/',
  path: '/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireIndexRoute = QuestionnaireIndexRouteImport.update({
  id: '/questionnaire/',
  path: '/questionnaire/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostPostsRoute = AdminPostPostsRouteImport.update({
=======
const QuestionnaireSegmentedIndexRoute =
  QuestionnaireSegmentedIndexRouteImport.update({
    id: '/questionnaire/segmented/',
    path: '/questionnaire/segmented/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedPostPostsRoute = AuthedPostPostsRouteImport.update({
>>>>>>> 4bc6defafec6f7a5b40d3e276d0da4e09cc162ad
  id: '/post/posts',
  path: '/post/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostPostsIndexRoute = AdminPostPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/success': typeof SuccessIndexRoute
<<<<<<< HEAD
  '/admin/post/posts': typeof AdminPostPostsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/post/posts/': typeof AdminPostPostsIndexRoute
=======
  '/post/posts': typeof AuthedPostPostsRouteWithChildren
  '/questionnaire/segmented': typeof QuestionnaireSegmentedIndexRoute
  '/post/posts/': typeof AuthedPostPostsIndexRoute
>>>>>>> 4bc6defafec6f7a5b40d3e276d0da4e09cc162ad
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/success': typeof SuccessIndexRoute
<<<<<<< HEAD
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/post/posts': typeof AdminPostPostsIndexRoute
=======
  '/questionnaire/segmented': typeof QuestionnaireSegmentedIndexRoute
  '/post/posts': typeof AuthedPostPostsIndexRoute
>>>>>>> 4bc6defafec6f7a5b40d3e276d0da4e09cc162ad
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/success/': typeof SuccessIndexRoute
<<<<<<< HEAD
  '/admin/post/posts': typeof AdminPostPostsRouteWithChildren
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/post/posts/': typeof AdminPostPostsIndexRoute
=======
  '/_authed/post/posts': typeof AuthedPostPostsRouteWithChildren
  '/questionnaire/segmented/': typeof QuestionnaireSegmentedIndexRoute
  '/_authed/post/posts/': typeof AuthedPostPostsIndexRoute
>>>>>>> 4bc6defafec6f7a5b40d3e276d0da4e09cc162ad
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/logout'
    | '/signup'
    | '/questionnaire'
    | '/success'
<<<<<<< HEAD
    | '/admin/post/posts'
    | '/admin/dashboard'
    | '/admin/post/posts/'
=======
    | '/post/posts'
    | '/questionnaire/segmented'
    | '/post/posts/'
>>>>>>> 4bc6defafec6f7a5b40d3e276d0da4e09cc162ad
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/logout'
    | '/signup'
    | '/questionnaire'
    | '/success'
<<<<<<< HEAD
    | '/admin/dashboard'
    | '/admin/post/posts'
=======
    | '/questionnaire/segmented'
    | '/post/posts'
>>>>>>> 4bc6defafec6f7a5b40d3e276d0da4e09cc162ad
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/logout'
    | '/signup'
    | '/questionnaire/'
    | '/success/'
<<<<<<< HEAD
    | '/admin/post/posts'
    | '/admin/dashboard/'
    | '/admin/post/posts/'
=======
    | '/_authed/post/posts'
    | '/questionnaire/segmented/'
    | '/_authed/post/posts/'
>>>>>>> 4bc6defafec6f7a5b40d3e276d0da4e09cc162ad
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  QuestionnaireIndexRoute: typeof QuestionnaireIndexRoute
  SuccessIndexRoute: typeof SuccessIndexRoute
  QuestionnaireSegmentedIndexRoute: typeof QuestionnaireSegmentedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/': {
      id: '/success/'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/': {
      id: '/questionnaire/'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
=======
    '/questionnaire/segmented/': {
      id: '/questionnaire/segmented/'
      path: '/questionnaire/segmented'
      fullPath: '/questionnaire/segmented'
      preLoaderRoute: typeof QuestionnaireSegmentedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/post/posts': {
      id: '/_authed/post/posts'
      path: '/post/posts'
      fullPath: '/post/posts'
      preLoaderRoute: typeof AuthedPostPostsRouteImport
      parentRoute: typeof AuthedRouteRoute
>>>>>>> 4bc6defafec6f7a5b40d3e276d0da4e09cc162ad
    }
    '/admin/post/posts': {
      id: '/admin/post/posts'
      path: '/post/posts'
      fullPath: '/admin/post/posts'
      preLoaderRoute: typeof AdminPostPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/post/posts/': {
      id: '/admin/post/posts/'
      path: '/'
      fullPath: '/admin/post/posts/'
      preLoaderRoute: typeof AdminPostPostsIndexRouteImport
      parentRoute: typeof AdminPostPostsRoute
    }
  }
}

interface AdminPostPostsRouteChildren {
  AdminPostPostsIndexRoute: typeof AdminPostPostsIndexRoute
}

const AdminPostPostsRouteChildren: AdminPostPostsRouteChildren = {
  AdminPostPostsIndexRoute: AdminPostPostsIndexRoute,
}

const AdminPostPostsRouteWithChildren = AdminPostPostsRoute._addFileChildren(
  AdminPostPostsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminPostPostsRoute: typeof AdminPostPostsRouteWithChildren
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPostPostsRoute: AdminPostPostsRouteWithChildren,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  QuestionnaireIndexRoute: QuestionnaireIndexRoute,
  SuccessIndexRoute: SuccessIndexRoute,
  QuestionnaireSegmentedIndexRoute: QuestionnaireSegmentedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
