/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessIndexRouteImport } from './routes/success/index'
import { Route as QuestionnaireIndexRouteImport } from './routes/questionnaire/index'
import { Route as QuestionnaireSegmentedIndexRouteImport } from './routes/questionnaire/segmented/index'
import { Route as AdminResponsesIndexRouteImport } from './routes/admin/responses/index'
import { Route as AdminQuestionnairesIndexRouteImport } from './routes/admin/questionnaires/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as ApiVideoSplatRouteImport } from './routes/api/video/$'
import { Route as AdminResponsesResponseIdIndexRouteImport } from './routes/admin/responses/$responseId/index'
import { Route as AdminQuestionnairesQuestionnaireIdIndexRouteImport } from './routes/admin/questionnaires/$questionnaireId/index'
import { Route as AdminQuestionnairesQuestionnaireIdQuestionIdIndexRouteImport } from './routes/admin/questionnaires/$questionnaireId/$questionId/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessIndexRoute = SuccessIndexRouteImport.update({
  id: '/success/',
  path: '/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireIndexRoute = QuestionnaireIndexRouteImport.update({
  id: '/questionnaire/',
  path: '/questionnaire/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireSegmentedIndexRoute =
  QuestionnaireSegmentedIndexRouteImport.update({
    id: '/questionnaire/segmented/',
    path: '/questionnaire/segmented/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminResponsesIndexRoute = AdminResponsesIndexRouteImport.update({
  id: '/responses/',
  path: '/responses/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuestionnairesIndexRoute =
  AdminQuestionnairesIndexRouteImport.update({
    id: '/questionnaires/',
    path: '/questionnaires/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiVideoSplatRoute = ApiVideoSplatRouteImport.update({
  id: '/api/video/$',
  path: '/api/video/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResponsesResponseIdIndexRoute =
  AdminResponsesResponseIdIndexRouteImport.update({
    id: '/responses/$responseId/',
    path: '/responses/$responseId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminQuestionnairesQuestionnaireIdIndexRoute =
  AdminQuestionnairesQuestionnaireIdIndexRouteImport.update({
    id: '/questionnaires/$questionnaireId/',
    path: '/questionnaires/$questionnaireId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute =
  AdminQuestionnairesQuestionnaireIdQuestionIdIndexRouteImport.update({
    id: '/questionnaires/$questionnaireId/$questionId/',
    path: '/questionnaires/$questionnaireId/$questionId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/success': typeof SuccessIndexRoute
  '/api/video/$': typeof ApiVideoSplatRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/questionnaires': typeof AdminQuestionnairesIndexRoute
  '/admin/responses': typeof AdminResponsesIndexRoute
  '/questionnaire/segmented': typeof QuestionnaireSegmentedIndexRoute
  '/admin/questionnaires/$questionnaireId': typeof AdminQuestionnairesQuestionnaireIdIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdIndexRoute
  '/admin/questionnaires/$questionnaireId/$questionId': typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/success': typeof SuccessIndexRoute
  '/api/video/$': typeof ApiVideoSplatRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/questionnaires': typeof AdminQuestionnairesIndexRoute
  '/admin/responses': typeof AdminResponsesIndexRoute
  '/questionnaire/segmented': typeof QuestionnaireSegmentedIndexRoute
  '/admin/questionnaires/$questionnaireId': typeof AdminQuestionnairesQuestionnaireIdIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdIndexRoute
  '/admin/questionnaires/$questionnaireId/$questionId': typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/success/': typeof SuccessIndexRoute
  '/api/video/$': typeof ApiVideoSplatRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/questionnaires/': typeof AdminQuestionnairesIndexRoute
  '/admin/responses/': typeof AdminResponsesIndexRoute
  '/questionnaire/segmented/': typeof QuestionnaireSegmentedIndexRoute
  '/admin/questionnaires/$questionnaireId/': typeof AdminQuestionnairesQuestionnaireIdIndexRoute
  '/admin/responses/$responseId/': typeof AdminResponsesResponseIdIndexRoute
  '/admin/questionnaires/$questionnaireId/$questionId/': typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/logout'
    | '/signup'
    | '/questionnaire'
    | '/success'
    | '/api/video/$'
    | '/admin/dashboard'
    | '/admin/questionnaires'
    | '/admin/responses'
    | '/questionnaire/segmented'
    | '/admin/questionnaires/$questionnaireId'
    | '/admin/responses/$responseId'
    | '/admin/questionnaires/$questionnaireId/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/logout'
    | '/signup'
    | '/questionnaire'
    | '/success'
    | '/api/video/$'
    | '/admin/dashboard'
    | '/admin/questionnaires'
    | '/admin/responses'
    | '/questionnaire/segmented'
    | '/admin/questionnaires/$questionnaireId'
    | '/admin/responses/$responseId'
    | '/admin/questionnaires/$questionnaireId/$questionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/logout'
    | '/signup'
    | '/questionnaire/'
    | '/success/'
    | '/api/video/$'
    | '/admin/dashboard/'
    | '/admin/questionnaires/'
    | '/admin/responses/'
    | '/questionnaire/segmented/'
    | '/admin/questionnaires/$questionnaireId/'
    | '/admin/responses/$responseId/'
    | '/admin/questionnaires/$questionnaireId/$questionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  QuestionnaireIndexRoute: typeof QuestionnaireIndexRoute
  SuccessIndexRoute: typeof SuccessIndexRoute
  ApiVideoSplatRoute: typeof ApiVideoSplatRoute
  QuestionnaireSegmentedIndexRoute: typeof QuestionnaireSegmentedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/': {
      id: '/success/'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/': {
      id: '/questionnaire/'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/segmented/': {
      id: '/questionnaire/segmented/'
      path: '/questionnaire/segmented'
      fullPath: '/questionnaire/segmented'
      preLoaderRoute: typeof QuestionnaireSegmentedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/responses/': {
      id: '/admin/responses/'
      path: '/responses'
      fullPath: '/admin/responses'
      preLoaderRoute: typeof AdminResponsesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/questionnaires/': {
      id: '/admin/questionnaires/'
      path: '/questionnaires'
      fullPath: '/admin/questionnaires'
      preLoaderRoute: typeof AdminQuestionnairesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/video/$': {
      id: '/api/video/$'
      path: '/api/video/$'
      fullPath: '/api/video/$'
      preLoaderRoute: typeof ApiVideoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/responses/$responseId/': {
      id: '/admin/responses/$responseId/'
      path: '/responses/$responseId'
      fullPath: '/admin/responses/$responseId'
      preLoaderRoute: typeof AdminResponsesResponseIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/questionnaires/$questionnaireId/': {
      id: '/admin/questionnaires/$questionnaireId/'
      path: '/questionnaires/$questionnaireId'
      fullPath: '/admin/questionnaires/$questionnaireId'
      preLoaderRoute: typeof AdminQuestionnairesQuestionnaireIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/questionnaires/$questionnaireId/$questionId/': {
      id: '/admin/questionnaires/$questionnaireId/$questionId/'
      path: '/questionnaires/$questionnaireId/$questionId'
      fullPath: '/admin/questionnaires/$questionnaireId/$questionId'
      preLoaderRoute: typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminQuestionnairesIndexRoute: typeof AdminQuestionnairesIndexRoute
  AdminResponsesIndexRoute: typeof AdminResponsesIndexRoute
  AdminQuestionnairesQuestionnaireIdIndexRoute: typeof AdminQuestionnairesQuestionnaireIdIndexRoute
  AdminResponsesResponseIdIndexRoute: typeof AdminResponsesResponseIdIndexRoute
  AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute: typeof AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminQuestionnairesIndexRoute: AdminQuestionnairesIndexRoute,
  AdminResponsesIndexRoute: AdminResponsesIndexRoute,
  AdminQuestionnairesQuestionnaireIdIndexRoute:
    AdminQuestionnairesQuestionnaireIdIndexRoute,
  AdminResponsesResponseIdIndexRoute: AdminResponsesResponseIdIndexRoute,
  AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute:
    AdminQuestionnairesQuestionnaireIdQuestionIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  QuestionnaireIndexRoute: QuestionnaireIndexRoute,
  SuccessIndexRoute: SuccessIndexRoute,
  ApiVideoSplatRoute: ApiVideoSplatRoute,
  QuestionnaireSegmentedIndexRoute: QuestionnaireSegmentedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
