/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessIndexRouteImport } from './routes/success/index'
import { Route as QuestionnaireIndexRouteImport } from './routes/questionnaire/index'
import { Route as AuthedPostPostsRouteImport } from './routes/_authed/post/posts'
import { Route as AuthedPostPostsIndexRouteImport } from './routes/_authed/post/posts.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessIndexRoute = SuccessIndexRouteImport.update({
  id: '/success/',
  path: '/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireIndexRoute = QuestionnaireIndexRouteImport.update({
  id: '/questionnaire/',
  path: '/questionnaire/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPostPostsRoute = AuthedPostPostsRouteImport.update({
  id: '/post/posts',
  path: '/post/posts',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPostPostsIndexRoute = AuthedPostPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/success': typeof SuccessIndexRoute
  '/post/posts': typeof AuthedPostPostsRouteWithChildren
  '/post/posts/': typeof AuthedPostPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/success': typeof SuccessIndexRoute
  '/post/posts': typeof AuthedPostPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/success/': typeof SuccessIndexRoute
  '/_authed/post/posts': typeof AuthedPostPostsRouteWithChildren
  '/_authed/post/posts/': typeof AuthedPostPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/questionnaire'
    | '/success'
    | '/post/posts'
    | '/post/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/questionnaire'
    | '/success'
    | '/post/posts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/questionnaire/'
    | '/success/'
    | '/_authed/post/posts'
    | '/_authed/post/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  QuestionnaireIndexRoute: typeof QuestionnaireIndexRoute
  SuccessIndexRoute: typeof SuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/': {
      id: '/success/'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/': {
      id: '/questionnaire/'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/post/posts': {
      id: '/_authed/post/posts'
      path: '/post/posts'
      fullPath: '/post/posts'
      preLoaderRoute: typeof AuthedPostPostsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/post/posts/': {
      id: '/_authed/post/posts/'
      path: '/'
      fullPath: '/post/posts/'
      preLoaderRoute: typeof AuthedPostPostsIndexRouteImport
      parentRoute: typeof AuthedPostPostsRoute
    }
  }
}

interface AuthedPostPostsRouteChildren {
  AuthedPostPostsIndexRoute: typeof AuthedPostPostsIndexRoute
}

const AuthedPostPostsRouteChildren: AuthedPostPostsRouteChildren = {
  AuthedPostPostsIndexRoute: AuthedPostPostsIndexRoute,
}

const AuthedPostPostsRouteWithChildren = AuthedPostPostsRoute._addFileChildren(
  AuthedPostPostsRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedPostPostsRoute: typeof AuthedPostPostsRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedPostPostsRoute: AuthedPostPostsRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  QuestionnaireIndexRoute: QuestionnaireIndexRoute,
  SuccessIndexRoute: SuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
